### ISSUE TITLE
Locale problem

### ISSUE THREAD

**Issue by fredguth** [HTMLElements/smart-calendar#1]
In portuguese it is not common (as in english)  to have 2 chars of the week day in a calendar.  We either use one char "D S T Q Q S S" or 3 chars "DOM SEG TER QUA QUI SEX SÁB".

How can I change this locale messages? I prefer to use only one char.
How can I check all messages in portuguese to see if they are correct?

**Comment by DimitarD** [comment]
Thank you for your feedback. Please try setting the Calendar property **dayNameFormat** (day-name-format) to either _'narrow'_ (for one character) or _'short'_ (for three characters).

Messages in the Calendar component are automatically localized by the JavaScript [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) object and conform to approved standards.

**Comment by fredguth** [comment]
Thanks
